## Hi there 👋

I'm Dickson Houmbie, an aspiring AI/ML enthusiast with a growing interest in Health AI and Biomedical Engineering. Currently, I'm expanding my knowledge by diving into **TensorFlow** to enhance my skills in deep learning, after completing the **Data Science online course from Zero To Mastery Academy**.

My journey into healthcare AI began with a **heart disease prediction project**, where I applied machine learning techniques to healthcare data. This project sparked my interest in using AI to solve real-world problems in healthcare, and I'm eager to continue exploring the field.

While I'm just getting started, I'm passionate about the potential of AI in healthcare and biomedical engineering. I'm always open to new challenges, collaborations, and opportunities to learn and grow. Let's connect and build impactful solutions together!


<!--
**Nosckid/Nosckid** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->
